.PHONY: all
all: kinematics workspace singularities

.PHONY: kinematics
kinematics:
	@echo "Running kinematics simulation..."
	@python assignment1/kinematics.py


.PHONY: workspace
workspace:
	@echo "Running workspace simulation..."
	@python assignment1/workspace.py

.PHONY: singularities
singularities:
	@echo "Running singularities simulation..."
	@python assignment1/singularities.py

.PHONY: kuka
kuka:
	@echo "Running KUKA simulation..."
	@python assignment1/kuka.py